TRAIN_SCRIPT=/uufs/chpc.utah.edu/common/home/u0002613/AbsoluteQuantification/AbsoluteQuantification/model_training/train_model.py
CONFIG=/uufs/chpc.utah.edu/common/home/u0002613/AbsoluteQuantification/AbsoluteQuantification/model_training/idbd_half_log_titration_urine_extraction/config_half_log_with_fungal_no_cutoffs.yaml
python $TRAIN_SCRIPT $CONFIG