TRAIN_SCRIPT=/home/jmontgomery/AbsoluteQuantification/model_training/train_model.py
CONFIG=/home/jmontgomery/AbsoluteQuantification/model_training/synergy_t4_2020-01-14/config_remove_poor_performers.yaml
python $TRAIN_SCRIPT $CONFIG